sudo: required

language: go

env:
  global:
    - MAKEFLAGS="-j4"
    - GOARCH=amd64
    - DB_HOST=127.0.0.1
    - POSTGRESQL_VERSION=9.6
    - MONGO_VERSION=3.0
    - MYSQL_VERSION=5.7
    - MSSQL_VERSION=latest

notifications:
  email: false

go:
  - "1.9"
  - "1.10"
  - "1.11"

services:
  - docker

addons:
  apt:
    packages:
    - freetds-bin

before_install:
  - sudo service mysql stop &
  - sudo service postgresql stop &
  - wait

install:
  - mkdir -p $GOPATH/src/upper.io
  - mv $PWD $GOPATH/src/upper.io/db.v3
  - cd $GOPATH/src/upper.io/db.v3
  - go get -t -v -d ./...
  - go get -v github.com/cznic/ql/ql
  - export TRAVIS_BUILD_DIR=$GOPATH/src/upper.io/db.v3

env:
  - TEST_CMD="make test"
  - TEST_CMD="make benchmark"

script:
  - docker pull postgres:$POSTGRESQL_VERSION &
  - docker pull microsoft/mssql-server-linux:$MSSQL_VERSION &
  - docker pull mongo:$MONGO_VERSION &
  - docker pull mysql:$MYSQL_VERSION &
  - wait
  - docker run --rm -d -e 'POSTGRES_USER=upperio_tests' -e 'POSTGRES_PASSWORD=upperio_secret' -p $DB_HOST:5432:5432 --name postgres postgres:$POSTGRESQL_VERSION &
  - docker run --rm -d -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=my$Password' -p $DB_HOST:1433:1433 --name mssql microsoft/mssql-server-linux:$MSSQL_VERSION &
  - docker run --rm -d -e "MYSQL_USER=upperio_tests" -e "MYSQL_PASSWORD=upperio_secret" -e "MYSQL_ALLOW_EMPTY_PASSWORD=1" -e "MYSQL_DATABASE=upperio_tests" -p $DB_HOST:3306:3306 --name mysql mysql:$MYSQL_VERSION &
  - docker run --rm -d -e "MONGO_USER=upperio_tests" -e "MONGO_PASSWORD=upperio_secret" -e "MONGO_DATABASE=upperio_tests" -p $DB_HOST:27017:27017 --name mongo mongo:$MONGO_VERSION &
  - wait
  - sleep 10
  - docker exec -it mysql bash -c 'mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql'
  - bash -c "$TEST_CMD"
